# Error Handling

-   One of the most interesting things about exceptions is that they define a scope within your
    program. When you execute code in the try portion of a try-catch-finally statement, you
    are stating that execution can abort at any point and then resume at the catch.
